from .usuario import *
from .postulante import *
from .evaluacion import *
from .documento import *
from .entrevista import *
from .firma import *
from .derechohabiente import *
from .bancario import *
from .pensionario import *
from .capacitacion import *
from .ia import *
